# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190403_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 3, 12, 51, 43, 196967, tzinfo=utc)),
        ),
    ]
