# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-06 15:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 4, 6, 15, 8, 1, 52595, tzinfo=utc))),
                ('body', models.TextField(default='')),
                ('writer', models.TextField(default='')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
